[package]
name = "rustlight"
version = "0.2.0"
authors = ["Adrien Gruson <adrien.gruson@gmail.com>"]
edition = "2018"

[[bin]]
name = "rustlight"
doc = false

[features]
# No default features are enable by default
default = ["image", "embree-accel", "pbrt"]
pbrt = ["pbrt_rs"]
embree-accel = ["embree"]

[dependencies]
image = { version =  "*", optional = true }
rayon = "*"
rand = "*"
tobj = "*"
#embree-rs = { version = "*" , optional = true }
embree = { git = "https://github.com/beltegeuse/embree-rs", optional = true }
serde = "1.0"
serde_derive = "1.0" 
serde_json = "1.0"
byteorder = "*"
clap = "*"
pbr = "*"
log = "*"
env_logger = "*"
# To know number of threads
num_cpus = "*"
# - openexr image format (output)
openexr = { path = "C:/Users/xy_zm/.cargo/git/checkouts/openexr-rs-1b2cea68adc6ad18/735a4bb", optional = true }
# - pbrt image format (input)
pbrt_rs = { git = "https://github.com/beltegeuse/pbrt_rs", optional = true }

[dependencies.cgmath]
version = "*"
features = ["serde"]
