[package]
name = "rustlight"
version = "0.0.1"
authors = ["Adrien Gruson <adrien.gruson@gmail.com>"]

[[bin]]
name = "rustlight"
doc = false

[dependencies]
image = "0.18.0"
rayon = "0.9.0"
rand = "0.4.2"
tobj = "*"
embree = { git = "https://github.com/beltegeuse/embree-rs-1.git" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.cgmath]
version = "0.16.0"
features = ["serde"]