[package]
name = "rustlight"
version = "0.0.3"
authors = ["Adrien Gruson <adrien.gruson@gmail.com>"]

[[bin]]
name = "rustlight"
doc = false

[dependencies]
image = "0.18.0"
rayon = "1.0.0"
rand = "0.4.2"
tobj = "*"
embree-rs = { git = "https://github.com/beltegeuse/embree-rs.git" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
byteorder = "*"
clippy = { version = "*", optional = true }
clap = "2.31.1"

[dependencies.cgmath]
version = "0.16.0"
features = ["serde"]