[package]
name = "rustlight"
version = "0.2.0"
authors = ["Adrien Gruson <adrien.gruson@gmail.com>"]
edition = "2018"

[features]
# No default features are enable by default
default = ["image", "embree-rs", "pbrt"]
pbrt = ["pbrt_rs"]
embree = ["embree-rs"]
progress-bar = ["pbr"]

[dependencies]
byteorder = "*"
embree-rs = { version = "*" , optional = true }
image = { version =  "*", optional = true }
openexr = { version = "*", optional = true }
log = "*"
rand = "*"
rayon = "*"
serde = "1.0"
serde_derive = "1.0" 
serde_json = "1.0"
tobj = "*"
pbr = { version = "*", optional = true }
pbrt_rs = { git = "https://github.com/beltegeuse/pbrt_rs", optional = true }

[dependencies.cgmath]
version = "*"
features = ["serde"]

[dev-dependencies]
clap = "*"
env_logger = "*"
num_cpus = "*"