[package]
name = "rustlight"
version = "0.2.0"
authors = ["Adrien Gruson <adrien.gruson@gmail.com>"]
edition = "2018"

[features]
default = ["image", "pbrt", "progress-bar", "mitsuba"]
pbrt = ["pbrt_rs"]
mitsuba = ["mitsuba_rs"]
embree = ["embree-rs"]
progress-bar = ["pbr"]

[dependencies]
byteorder = "*"
cgmath = { version = "*", features = ["serde"] }
embree-rs = { version = "*" , optional = true }
image = { version =  "*", optional = true }
openexr = { version = "*", optional = true }
log = "*"
rand = { version = "*", features = ["small_rng"] }
rayon = "*"
serde = "1.0"
serde_derive = "1.0" 
serde_json = "1.0"
tobj = "*"
pbr = { version = "*", optional = true }
pbrt_rs = { git = "https://github.com/beltegeuse/pbrt_rs", optional = true }
mitsuba_rs = { git = "https://github.com/beltegeuse/mitsuba_rs", optional = true }
lazy_static = "1.4"
assert_approx_eq = "1.1"

[dev-dependencies]
clap = "*"
env_logger = "*"
num_cpus = "*"